kubewarden/policy-sdk-rust

src/lib.rs
src/response.rs

Besides the message, the Kubernetes API server allows webhooks to
specify the HTTP code when rejecting a request.

Add ability to reject request with a specific HTTP code

---

Cargo.toml
src/cluster_context.rs
src/lib.rs

Depends on https://github.com/chimera-kube/policy-server/pull/39
Add functionality to the SDK so it is able to read `Namespace`,
`Ingress` and `Service` resources in order for a policy to take
contextual decisions.
This is a first approach, and there are plans to generalize this and
avoid hardcoded types.

Implement cluster context awareness

---

src/cluster_context.rs

Depending on the namespace filter, it could happen that ingresses and
services could be duplicated with the same name on different
namespaces. Provide a signature for this methods that resemble this
option in a natural way.
The Vec could be empty, in which case no resource was found with that
name, one element or more than one element if a resource with the same
name exists on different namespaces and the consumer call is not
filtering on a specific namespace.

Return a Vec when a resource is requested by name

---

Cargo.toml
src/lib.rs
src/response.rs

Change `mutated_object` attribute of the `ValidationResponse` to be a native JSON object instead of a string holding the a serialized JSON document.
Once this is merged I'll update the policy-evaluator crate to handle the new format

Change the API of the mutated object response

---

Cargo.toml
src/lib.rs
src/metadata.rs

This PR introduces the concept of "protocol version". This is a versioning scheme for policies, that describes the communication protocol used by the policy to communicate with the policy evaluator.
Needed to fix https://github.com/kubewarden/policy-sdk-rust/issues/11

Protocol version

---

Cargo.toml
src/metadata.rs

Implement the Display trait for `ProtocolVersion`. This simplifies the printing of protocol version inside of kwctl
Once this is merged, I'll release a new version of this crate.

Implement display for protocol version

---

src/lib.rs
src/non_wasm.rs

This functions have to be linked if the SDK is used: implement empty
stubs, so the linking process always work.

Stub waPC functions for other targets than wasm32

---

.github/dependabot.yml
.github/workflows/security-audit-cron.yml
.github/workflows/security-audit-reactive.yml

Enable dependabot and add the usual GH actions that deal with security tasks via `cargo audit`

Add more automation

---

Cargo.toml
src/host_capabilities/mod.rs
src/host_capabilities/verification.rs
src/lib.rs

Add two new methods that can be called from the policies: `verify_pub_keys_image()` and  `verify_keyless_exact_match() ` They will return a `VerificationResponse` which contains a boolean indicating if it is trusted and the digest.
Fix https://github.com/kubewarden/policy-server/issues/99
Superseeds https://github.com/kubewarden/policy-sdk-rust/pull/32

Sigstore container verification

---

Cargo.toml

Starting from k8s-openapi v0.14, it is NOT recommended to be explicit about the kubernetes features to be used when building a library. That's because the final version of the k8s API to be supported must be made by the consumer of the library.
Otherwise it's possible to end up in situations like:
* kubewarden-policy-sdk enables the `v1_22` feature of k8s-openapi
* `consumer-foo` requires k8s-openapi too but enables the `v1_23` feature A build error is then raised by cargo because the same version must be picked by all the crates making use of k8s-openapi.
Because of that, no feature is chosen inside of the `dependencies` section. This however can lead to issues when executing commands like cargo `build|check|doc`. That's because the `k8s-openapi` is specified again inside of the …

Fix k8s-openapi dependency to break building of rust policies

---

Cargo.toml
src/host_capabilities/verification.rs

Message returned with this chage is:
```
Pod nginx is not accepted: verification of image ghcr.io/kubewarden/test-verify-image-signatures:unsigned failed: Host error: Callback evaluation failure: no signatures found for image: ghcr.io/kubewarden/test-verify-image-signatures:unsigned 
```
Fix https://github.com/kubewarden/policy-fetcher/issues/85

remove debug of trait error when invoking wapc verify

---

Cargo.toml

We need to update the k8s-openapi dependency there, in order to update it at higher levels.
I also updated the wapc-guest code, the project bumped from v0.4.0 -> v1.0.0 without breaking changes.

Release v0.5.1

---

Cargo.toml
src/lib.rs
src/response.rs

- feat!: make k8s-openapi dependency optional
- feat: export wapc-guest
- feat!: validation response - offer all k8s fields
- Tag v0.6.0

refactorings

---

src/host_capabilities/mod.rs
src/host_capabilities/verification.rs

Add new API:
`pub CallbackRequestType::SigstoreGithubActionsVerify{}`
`pub fn verify_keyless_github_actions()`
`pub CallbackRequestType::SigstoreKeylessPrefixVerify{}`
`pub fn verify_keyless_prefix_match()`
Consumers of the SDK can levarage this new API call to ask for
verification of signatures done with jobs in Github Actions, and to ask for
verification of signatures where the subject needs to be a URL prefix of
the signature subject, respectively.
This API addition is leveraged by policy-evaluator to perform the
callbacks in the wasm host.
Needed by https://github.com/kubewarden/policy-sdk-rust/issues/41
Needed by https://github.com/kubewarden/policy-sdk-rust/issues/40

feat: Add callbacks for verification of GHA signatures, Url Prefix

---

Cargo.toml
src/host_capabilities/mod.rs
src/host_capabilities/verification.rs

Follow-up of https://github.com/kubewarden/policy-sdk-rust/pull/46, which I merged prematurely.

Bump to 0.6.1, fix typos and add docs strings

---

Cargo.toml
src/lib.rs

Adds a new function in the SDK to help policy developers to mutate pod spec from the high level resources (e.g. deployment, statefulset, replicaset, etc).
Fix #63

feat: function to mutate the pod spec.

---

Cargo.toml

Updates the Cargo.toml bumping the SDK version to v0.8.0. This version includes a new function to help policy authors to mutate Pod spec from high level resources types (e.g. deployment, replicaset, cronjob, etc).

Bump version v0.8.0

---

.github/workflows/tests.yml
Cargo.toml
Makefile
src/lib.rs
src/request.rs

When the default features are disabled, the k8s-openapi crate is no longer required.
The recent helpers introduced to deal with Kubernetes resources containing Pod didn't take that into account.
That causes the library to not compile properly when the imported without the default features.
This commit fixes this and extends our unit tests to ensure this won't happen again.

fix: handle default features being disabled

---

src/host_capabilities/crypto.rs
src/host_capabilities/mod.rs

Needed by https://github.com/kubewarden/policy-evaluator/issues/200.
This new sdk function verifies a cert against a passed cert_chain.
It uses the new host callback
`kubewarden/crypto/v1/is_certificate_trusted`.
The new `crypto` callback json request and response are specified in the new `crypto_v1` module.
Tested in policy-evaluator.

feat: Add host_capabilities::crypto::verify_cert()

---

src/host_capabilities/mod.rs
src/host_capabilities/verification.rs

Extend the sigstore verification capabilities to allow usage of certificates.
Required to implement https://github.com/kubewarden/verify-image-signatures/issues/39

sigstore cert verification

---

Cargo.toml
src/host_capabilities/crypto.rs
src/host_capabilities/mod.rs

Relates to https://github.com/kubewarden/verify-image-signatures/pull/47#discussion_r1034836373
Make `verify_cert()`, return `Result<SDK::BoolWithReason>`. Response either returns:
* `Ok(BoolWithReason::True)`.
* `Ok(BoolWithReason::False((reason))` with ``reason` such as "cert not trusted by cert
chain", or "cert expired".
* `Err(e)`, with `e` such as "cert not in PEM format", or "not_after
datetime not in RFC 3339 format".
Bump version to 0.8.5
No need.

fix!: Make `verify_cert()`, return `Result<BoolWithReason>` & bump version

---

Cargo.toml

* Update to latest version of the k8s-openapi crate
We need that to ensure the same version of k8s-openapi is being used by the entire stack

Tag v0.8.7

---

src/host_capabilities/verification.rs

This is required by the context aware feature, more specifically by the new callback handler proxy

refactor: derive Eq traits against some structs

---

Cargo.toml
src/request.rs

This is required to simplify the process of writing unit tests.

refactor: make some types serializable

---

Cargo.toml

Fix doc.rs builds: ensure the documentation is built
Fixes https://github.com/kubewarden/policy-sdk-rust/issues/88
I've tested the fix running doc.rs locally

0.9.3 release

---

Cargo.toml

Disable the default features of the chrono crate, by doing that we can get rid of the time v0.1 transitive dependency.
This is a version of time that is affected by a severe CVE
Once this is merged I'll tag the v0.9.5 release

remove time v0.1 dependency

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

Adds release-drafter workflow + config.
Tested the GH action in a fork.
The action is failing because the config file was not merged in main yet.
Closes #103

ci: add release-drafter

---

src/host_capabilities/crypto.rs

The 0.9.5 release of this crate broke the `v1/is_certificate_trusted` host capability.
The break was introduced by commit 3dbead4485f0618129835dbdc2d58fe231ee83f2 which has been reverted by this commit.
Fixes #105

fix: breaking change done by 0.9.5 release

---

.github/workflows/release.yml
Cargo.toml

Make release names created by release.yml workflow match what release-drafter.yml expects, so it can create the next draft correctly.
Not tested.
This gives us release names like `v1.7.0`, which is a change from history.
We could change the name in release drafter instead, to expect `Kubewarden Rust SDK v0.9.5` format for example, and open drafts with that format.

ci: Reuse release drafts when creating release 

---

src/host_capabilities/kubernetes.rs

Renames  `list_all_resources` to `list_resources_all`  
see: https://github.com/kubewarden/policy-evaluator/blob/29cb05045f0faa99bea09d5b58fa17a7ef56fdfa/src/runtimes/wapc/callback.rs#L181

fix: rename list all resources host call

---

Cargo.toml
src/host_capabilities/oci.rs

Adds a new capability function to allow users request the OCI image manifest to the given image name.
Fix #128

feat: image manifest capability

---

Cargo.toml
src/host_capabilities/mod.rs

`CertificateVerificationRequest{}.not_after` is an `Option`. if `Some`,
it is taken into account to check the certificate against the date,
here:
https://github.com/kubewarden/policy-evaluator/blob/71270655862d9f53bc23feafb3c4e9b4ed982bef/src/callback_handler/crypto.rs#L52-L54
Still, since this is a callback, it may happen that the guest caller
provides a `CertificateVerificationRequest{}` where its
`CertificateVerificationRequest{}.not_after` is present, yet set to the
empty string.
It would then deserialize to `Some("")` instead of `None`. This would
incorrectly skip the expiration check.
Hence, ensure that on (de)serialization on the host, we consider empty
strings as `None`.
CI
Another option is to, instead of checking this in the Rust SDK that gets used by the host, make sure that …

fix: CertificateVerificationRequest{}.not_after as None if empty

---

src/host_capabilities/oci.rs

Rename the OCI host capabilities functions to follow the standard `<verb>_<subject of the action>`.
Related to https://github.com/kubewarden/kubewarden.io/pull/212#issuecomment-1951992643

fix!: renames OCI capability functions.

---

Cargo.toml

Bump the version of the SDK to release the new host capability to fetch OCI image manifest and configuration and some dependencies updates.

chore: bump version to v0.11.0.

---

Cargo.toml
src/host_capabilities/mod.rs
src/host_capabilities/verification.rs

Change the Sigstore verifiers to use `BTreeMap` instead of `HashMap` to store annotations.
This is required by a change done by the latest version of the sigstore-rs crate.
This refactor breaks our Rust API, but it doesn't change the waPC one. These are just two different data structures used to represent hashes
I decided to change the SDK rather to avoid useless conversions inside of the callback handlers of waPC.
I'll tag the 0.13.0 release once this gets mergeed.

sigstore verifier refactor

---

Cargo.toml

Ensure the documentation shown on docs.rs cover all our code, even the one that is enabled by non-default features.
Once this is merged I'll tag the 0.13.2 release

show all features on docrs

---

Cargo.toml

Release 1.13.3 consuming oci-spec 0.8.0.
This is needed by some policies that consume oci-spec on their own, e.g: https://github.com/kubewarden/user-group-psp-policy/pull/142.
CI

build: Bump version to 0.13.3

---

.github/workflows/tests.yml

Removes the deprecated actions-rs/cargo Github action used to run cargo commands.
Related to https://github.com/kubewarden/kubewarden-controller/issues/1092

fix(deps): remove deprecated actions-rs/cargo Github action.

---

.github/workflows/release.yml
.github/workflows/tests.yml

Removes the deprecated actions-rs/toolchain Github actions used to setup Rust toolchains. Replacing it by calls to the rustup command directly relying on the binaries installed in the workflow runner.
Related to https://github.com/kubewarden/kubewarden-controller/issues/1093

 chore: remove actions-rs/toolchain github action.

---

.github/workflows/security-audit-cron.yml
.github/workflows/security-audit-reactive.yml

Replace the deprecated actions-rs/audit-check GHA by a fork under the RustSec organization which is updated and more active.
This is not a final fix for the https://github.com/kubewarden/kubewarden-controller/issues/1091 issue because this action is not in our GHA allowed list. However, while we wait for the security team evaluation of the Rustsec action, let's use it because it has recent [updates](https://github.com/rustsec/audit-check/releases)

chore(deps): use rustsec/audit-check GHA.

---

Cargo.toml
src/crd/policies/admission_policy.rs
src/crd/policies/cluster_admission_policy.rs

Updates the AdmissionPolicySpec and ClusterAdmissionPolicySpec struct adding the new `message` field. This field is used to customize the error message returned by the policy.
Fix https://github.com/kubewarden/kubewarden-controller/issues/1141

feat: custom error message field.

---

src/host_capabilities/kubernetes.rs

Updates the function exposing the kubernetes/can-i host capability to follow the same standard of the other capabilities. The function will recive the request object as the argument.

fix(kubernetes/can-i): follow other capabilities function signatures.

---

Cargo.toml

Reverts kubewarden/policy-sdk-rust#175
This is because the bump to schemars v1 needs to happen in lockstep with the rest of dependencies, such as k8s-openapi (which has [bumped](https://github.com/Arnavion/k8s-openapi/commit/e9a9eaf672cf700ee78bd6f267fefc5efa571c7a) it but it hasn't been released yet).
This is only discovered once we consume the sdk via policy-evaluator, too.

Revert "fix(deps): update rust crate schemars to v1"

---

Cargo.toml

Bump the SDK version to v0.14.0 to release the new kubernetes/can-i host capability function.

chore: bump version to v0.14.0.

---

src/host_capabilities/kubernetes.rs

Updates the documentation for the can-i function and the object it receives as argument.
Related to https://github.com/kubewarden/kubewarden-controller/issues/902

chore(kubernetes/can-i): updates function documentation.

---

Cargo.toml

Updates the Cargo.toml file bumping the version to v0.14.1 releasing the fix in the documentation.

chore(Cargo.toml): bump v0.14.1 version.

---

src/host_capabilities/kubernetes.rs

Removes the k8s object field in the type describing the kubernetes/can-i request. Instead define individual fields for each of the supported configuration and build the SubjectAccessReview object in the policy-evaluator.
Related to https://github.com/kubewarden/kubewarden-controller/issues/902

fix(kubernetes/can-i): remove k8s object from can-i capability

---

Cargo.toml

Bump the SDK version in the Cargo.toml file to v0.14.2.

chore: v0.14.2 version bump.

---

.github/workflows/release.yml

Enable https://crates.io/docs/trusted-publishing
All the changes have already been done on crates.io

ci: enable crates.io trusted publishing

---

src/host_capabilities/mod.rs
src/logging/ser.rs

Updates the CertificateVerificationRequest struct to derive the Eq and PartialEq trait. This is required to allow the usage of the struct in the CallbackRequestType enum from policy-evaluator.
Required by https://github.com/kubewarden/policy-evaluator/pull/751

fix: CertificateVerificationRequest derive Eq and PartialEq.

---

Cargo.toml
src/host_capabilities/crypto.rs

Derive `Serialize` trait and implement the `Display` trait for some of the types of the `crypto` module.
This is required to implement some changes inside of policy-evaluator.
I'll tag a new release of the crate once this is merged.

refactor: derive extra traits for some crypto types

---

Cargo.toml
src/host_capabilities/mod.rs

Add the Eq and PartialEq derive for the CertificateVerificationResponse type to allow the comparision in policy-evaluator unit tests.
Related to https://github.com/kubewarden/policy-evaluator/issues/764

fix: allow equality comparision for CertificateVerificationResponse.

---

src/host_capabilities/crypto.rs

Update the documentation of the verify function to reflect the change done with https://github.com/kubewarden/policy-evaluator/pull/744

docs: update inline docs of crypto's host capability
